# Generated by Django 5.0.1 on 2024-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOMA', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
