# Generated by Django 5.0.1 on 2024-03-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOMA', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
