# Generated by Django 5.0.2 on 2024-03-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOMA', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products_mentioned',
        ),
    ]
