# Generated by Django 5.0.2 on 2024-04-19 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOMA', '0007_rename_author_post_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=datetime.datetime(2024, 4, 19, 5, 45, 12, 706594, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
